# Generated by Django 5.1.4 on 2024-12-17 19:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAddress',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'supplier_address',
            },
        ),
        migrations.CreateModel(
            name='SupplierPhone',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DDD', models.CharField(default='21', max_length=3)),
                ('number', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'SupplierPhone',
                'verbose_name_plural': 'SupplierPhones',
                'db_table': 'supplier_phone',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'user_address',
            },
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DDD', models.CharField(default='21', max_length=3)),
                ('number', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'UserPhone',
                'verbose_name_plural': 'UserPhones',
                'db_table': 'user_phone',
            },
        ),
    ]
