# Generated by Django 5.1.4 on 2025-01-18 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_supplier',
            field=models.ManyToManyField(related_name='products', through='store.ProductSupplier', to='users.supplier'),
        ),
        migrations.AddField(
            model_name='productsupplier',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_suppliers', to='store.store'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.subcategory'),
        ),
    ]
