# Generated by Django 5.1.4 on 2025-01-18 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategories',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 19, 28, 34, 840393)),
        ),
    ]
