# Generated by Django 5.1.4 on 2025-01-18 22:39

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_subcategories_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 19, 39, 56, 546637)),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
